name: Artifact demo

on: 
  workflow_dispatch:
  # schedule:
  # - cron: '*/1 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create a text file
      run: echo "Hello, world!" > hello.txt

    - name: Archive text file
      uses: actions/upload-artifact@v4
      with:
        name: hello-artifact
        path: hello.txt
  download:
    concurrency: #only 1 job can run at a time
      group: production-deployment 
      cancel-in-progress: false #true = cancel any job in progress / false = wait other job to finish
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download text file
        uses: actions/download-artifact@v4
        with:
          name: hello-artifact
          path: ./artifacts
        
      
      - name: Display content of the text file
        run: |
          cat ./artifacts/hello.txt 
          sleep 600s
