name: Manual Workflow with Inputs

# Triggers the workflow manually via GitHub UI
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the user'    # Description of the input
        required: true                     # Mark this input as required
        default: 'User'                    # Default value
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
        type: choice                       # Optional - input type can be 'string', 'boolean', or 'choice'
        options:                           # Available choices for this input
          - production
          - staging
          - development

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Use the input values
      - name: Show input parameters
        run: |
          echo "Hello, ${{ github.event.inputs.name }}"
          echo "Deploying to the ${{ github.event.inputs.environment }} environment"
